import Head from "next/head";
import Banner from "@/components/Home/Banner";
import NewArrivals from "@/components/Home/NewArrivals";
import Authenticity from "@/components/Home/Authenticity";
import MonthlyDeal from "@/components/Home/MonthlyDeal";
import Testimonials from "@/components/Home/Testimonials";
import { data } from "../request/data";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sneaker Vault</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Banner />
        <NewArrivals />
        <Authenticity />
        <MonthlyDeal />
        <Testimonials data={data} />
      </main>
    </>
  );
}
